In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
np.random.seed(0)

In [2]:
df = pd.read_csv('bikes.csv', index_col=0)
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [3]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
season,731.0,2.496580,1.110807,1.000000,2.000000,3.000000,3.000000,4.000000
yr,731.0,0.500684,0.500342,0.000000,0.000000,1.000000,1.000000,1.000000
mnth,731.0,6.519836,3.451913,1.000000,4.000000,7.000000,10.000000,12.000000
holiday,731.0,0.028728,0.167155,0.000000,0.000000,0.000000,0.000000,1.000000
weekday,731.0,2.997264,2.004787,0.000000,1.000000,3.000000,5.000000,6.000000
workingday,731.0,0.683995,0.465233,0.000000,0.000000,1.000000,1.000000,1.000000
weathersit,731.0,1.395349,0.544894,1.000000,1.000000,1.000000,2.000000,3.000000
temp,731.0,0.495385,0.183051,0.059130,0.337083,0.498333,0.655417,0.861667
atemp,731.0,0.474354,0.162961,0.079070,0.337842,0.486733,0.608602,0.840896
hum,731.0,0.627894,0.142429,0.000000,0.520000,0.626667,0.730209,0.972500
windspeed,731.0,0.190486,0.077498,0.022392,0.134950,0.180975,0.233214,0.507463
casual,731.0,848.176471,686.622488,2.000000,315.500000,713.000000,1096.000000,3410.000000
registered,731.0,3656.172367,1560.256377,20.000000,2497.000000,3662.000000,4776.500000,6946.000000
cnt,731.0,4504.348837,1937.211452,22.000000,3152.000000,4548.000000,5956.000000,8714.000000

In [4]:
df2 = df.loc[:,('season',
                'yr',
                'mnth',
                'holiday',
                'weekday',
                'workingday',
                'weathersit',
                'temp',
                'atemp',
                'hum',
                'windspeed',
                'cnt')]

df2.rename(columns={
                    'yr': 'year',
                    'mnth': 'month',
                    'weekday': 'week_day',
                    'workingday': 'working_day',
                    'weathersit': 'weather',
                    'temp': 'temperature',
                    'atemp': 'feeling_temperature',
                    'hum': 'humidity',
                    'windspeed': 'wind_speed',
                    'cnt': 'y'
                  }, inplace=True)
df2.head()

,season,year,month,holiday,week_day,working_day,weather,temperature,feeling_temperature,humidity,wind_speed,y
instant,,,,,,,,,,,,
1,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,985
2,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,801
3,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,1349
4,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,1562
5,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,1600

In [5]:
X = df2
y = X.pop('y')
X.head()

,season,year,month,holiday,week_day,working_day,weather,temperature,feeling_temperature,humidity,wind_speed
instant,,,,,,,,,,,
1,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446
2,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539
3,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309
4,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296
5,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900

In [6]:
y.head()

instant
1     985
2     801
3    1349
4    1562
5    1600
Name: y, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [8]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(548, 11) (183, 11) (548,) (183,)

In [9]:
y_train.dtypes

dtype('int64')

In [12]:
X_train_values = X_train.values.astype(float)
y2_train_values = y_train.values.astype(float)
print(X_train_values.dtype, y2_train_values.dtype)

float64 float64

In [13]:
from pyGPGOMEA import GPGOMEARegressor as GPG

In [14]:
ea = GPG(gomea=True, silent=False)
ea.fit(X_train_values, y2_train_values)

######################################### SETTINGS #######################################
# rng seed set to 435018
# parallel on 1 threads
# max generations -1
# max evaluations -1
# max time 60 (s)
# problem: symbolic regression (linear scaling enabled)
# population size: 500
# IMS active with 5 number of sub-generations and 1 number of generations for early stopping
# initial maximum tree height: 4
# syntactical uniqueness initialization tries: 1000
# maximum solution size: 1000
# evolutionary algorithm: GOMEA (FOS: Linkage Tree)
# elitism: 0
# uniform depth variation: enabled
##########################################################################################
 ! IMS:  Initialized run 0 with population size 500 and initial tree height 4
 % warning: maximum number of tries for syntactic unique initialization reached
 > generation 1 - best fit: 924122
 > generation 2 - best fit: 857111
 > generation 3 - best fit: 758630
 > generation 4 - best fit: 758630
 ! IMS:  Initialized run 1 with population size 1000 and initial tree height 4
 % warning: maximum number of tries for syntactic unique initialization reached
 > generation 5 - best fit: 743537
 > generation 6 - best fit: 724527
 > generation 7 - best fit: 709183
 > generation 8 - best fit: 707125
 > generation 9 - best fit: 698178
 > generation 10 - best fit: 689749
 > generation 11 - best fit: 683297
 > generation 12 - best fit: 672569
 > generation 13 - best fit: 664058
 > generation 14 - best fit: 664058
 > generation 15 - best fit: 660231
 > generation 16 - best fit: 660231
 > generation 17 - best fit: 649623
 > generation 18 - best fit: 649623
 > generation 19 - best fit: 649623
 > generation 20 - best fit: 647810
 > generation 21 - best fit: 647810
 > generation 22 - best fit: 647810
 > generation 23 - best fit: 647810
 > generation 24 - best fit: 647810
 ! IMS:  Initialized run 2 with population size 2000 and initial tree height 4
 % warning: maximum number of tries for syntactic unique initialization reached
 > generation 25 - best fit: 646778
 > generation 26 - best fit: 646778
 > generation 27 - best fit: 646778
 > generation 28 - best fit: 646778
 > generation 29 - best fit: 646778
 > generation 30 - best fit: 646778
 > generation 31 - best fit: 646778
 > generation 32 - best fit: 646778
 > generation 33 - best fit: 646778
 > generation 34 - best fit: 646778
 > generation 35 - best fit: 646778
 > generation 36 - best fit: 646778
 > generation 37 - best fit: 646778
 > generation 38 - best fit: 646778
 > generation 39 - best fit: 646778
 > generation 40 - best fit: 646778
 > generation 41 - best fit: 646778
 > generation 42 - best fit: 646778
 > generation 43 - best fit: 646778
 > generation 44 - best fit: 646778
 > generation 45 - best fit: 646778
 > generation 46 - best fit: 646778
 > generation 47 - best fit: 646778
 > generation 48 - best fit: 646778
 > generation 49 - best fit: 646778
 > generation 50 - best fit: 646778
 > generation 51 - best fit: 646778
 > generation 52 - best fit: 646778
 > generation 53 - best fit: 646778
 > generation 54 - best fit: 646778
 > generation 55 - best fit: 646778
 > generation 56 - best fit: 646778
 > generation 57 - best fit: 646778
 > generation 58 - best fit: 646778
 > generation 59 - best fit: 646778
 > generation 60 - best fit: 645016
 ! IMS: terminated run 0
 > generation 61 - best fit: 637733
 > generation 62 - best fit: 623821
 > generation 63 - best fit: 616034
 > generation 64 - best fit: 606010
 > generation 65 - best fit: 597536
 > generation 66 - best fit: 597536
 > generation 67 - best fit: 597536
 > generation 68 - best fit: 592060
 > generation 69 - best fit: 592060
 > generation 70 - best fit: 592060
 > generation 71 - best fit: 592035
 > generation 72 - best fit: 592035
 ! IMS:  Initialized run 3 with population size 4000 and initial tree height 4
 % warning: maximum number of tries for syntactic unique initialization reached
 > generation 73 - best fit: 592035
 > generation 74 - best fit: 592035
 > generation 75 - best fit: 592035
 > generation 76 - best fit: 592035
 > generation 77 - best fit: 592035
 > generation 78 - best fit: 592035
 > generation 79 - best fit: 591885
 > generation 80 - best fit: 591885
 > generation 81 - best fit: 591863
 > generation 82 - best fit: 588170
 > generation 83 - best fit: 584514
 > generation 84 - best fit: 577835
 > generation 85 - best fit: 577835
 > generation 86 - best fit: 577835
 > generation 87 - best fit: 577835
 > generation 88 - best fit: 577835
 > generation 89 - best fit: 577835
 > generation 90 - best fit: 577835
 > generation 91 - best fit: 577835
 > generation 92 - best fit: 577835
 > generation 93 - best fit: 577835
 > generation 94 - best fit: 577835
 > generation 95 - best fit: 577835
 > generation 96 - best fit: 577835
 > generation 97 - best fit: 577835
 > generation 98 - best fit: 577835
 > generation 99 - best fit: 577835
 -=-=-=-=-=-= TERMINATED =-=-=-=-=-=-
Best solution found:	((((x9p/x0)+(x10*x6))-(x1*sqrt(x7)))-((plog(x7)-(x7*x7))+((x6p/48.363000)*(x4-x0))))
Linear scaling coefficients:	a=8142.426507	b=-2830.271340
Number of nodes:	27
Train fit:	577835.001775
Running time:	60.120000
Evaluations:	1684143

GPGOMEARegressor(silent=False)

In [15]:
model = ea.get_model().replace("p/","/").replace("plog","log")

In [16]:
import sympy
model = str(sympy.simplify(model))

In [17]:
from sklearn.metrics import mean_squared_error

if model == "0":
	print("Warning: sympy couldn't make it due to numerical precision")
	# re-set to non-simplified model
	model = ea.get_model().replace("p/","/").replace("plog","log")
print('Model found:', model)
print('Evaluations taken:', ea.get_evaluations()) # care: this is not correct if multiple threads were used when fitting
print('Test RMSE:', np.sqrt( mean_squared_error(y_test, ea.predict(X_test.values)) ))

Model found: (x0*(2830.27134*x1*sqrt(x7) - 2830.27134*x10*x6 - 58.521418026177*x6*(x0 - x4) - 2830.27134*x7**2 + 2830.27134*log(x7) + 8142.426507) - 2830.27134*x9)/x0
Evaluations taken: 1684143
Test RMSE: 875.7630967657635

In [31]:
import pickle as pkl

with open("bikes_gp_gomea.pkl", "wb") as f:
    pkl.dump(ea, f)

In [54]:
print(ea)

GPGOMEARegressor(silent=False)

In [42]:
ea.predict(X_test.values[:5])

array([4778.00248884, 4729.71824138, 2148.9340536 ,  837.71932548,
       4184.44994707])

In [51]:
import pickle as pkl

with open("bikes_gp_gomea.pkl", "wb") as f:
    pkl.dump(ea, f)

In [52]:
with open("bikes_gp_gomea.pkl", "rb") as f2:
    ea2 = pkl.load(f2)
    print(ea2)

GPGOMEARegressor(silent=False)
######################################### SETTINGS #######################################
# rng seed set to 529502
# parallel on 1 threads
# max generations -1
# max evaluations -1
# max time 60 (s)
# problem: symbolic regression (linear scaling enabled)
# population size: 500
# IMS active with 5 number of sub-generations and 1 number of generations for early stopping
# initial maximum tree height: 4
# syntactical uniqueness initialization tries: 1000
# maximum solution size: 1000
# evolutionary algorithm: GOMEA (FOS: Linkage Tree)
# elitism: 0
# uniform depth variation: enabled
##########################################################################################

In [55]:
ea2.predict(X_test.values[:5])

TypeError: predict error: called before fitting